### ISSUE TITLE
Utworzenie wejścia i wyjścia w formacie JSON

### ISSUE THREAD

**Issue by maciejwawrzyniak24** [maciejwawrzyniak24/IO-projekt#10]

**Comment by Pszymczak00** [comment]
Format wejścia:
{
    "title": "Przyklad",
    "authors": [
        "Uzytkownik",
        "Komputer",
        "Aplikacja"
    ],
    "steps": [
        {
            "text": "Krok poziom pierwszy",
            "subSteps": [
                {
                    "text": "Krok poziom drugi",
                    "subSteps": []
                },
                {
                    "text": "Nastepny krok poziom drugi",
                    "subSteps": []
                }
            ]
        }
    ]
}
